### ISSUE TITLE
--cpu-threads-intensity option working?

### ISSUE THREAD

**Issue by Shai0Hulud** [doktor83/SRBMiner-Multi#57]
Hey, I am currently testing and comparing mining software. 

I can see that using different intensity (1 or 2) on cryptonight algorithms has different hashrate when using XMRig.

SRBMiner 0.7.9 (Windows 10 64bit) for example tells me that there are different options for --cpu-threads-intensity available, when starting:

"Algorithm 0 available values for --cpu-threads-intensity : 1, 2"

But even if I use this option in my batchfile, it still posts this message. So it's not really obvious if it is actually using the setting in my batchfile (when using this option, shouldnt the message be more like: "Algorithm 0: using cpu-threads-intensity 2"

Furthermore, I tried both 1 and 2 for algorithms that show a significant difference when using XMRig. But for SRBMiner, hashrates are the same, no matter if intensity 1 or 2 is used. This again leads me to believe that the option is not applied at all.

Regards!

**Comment by Shai0Hulud** [comment]
Just realized there is an update 0.8.0 - tested and same behaviour:

![image](https://user-images.githubusercontent.com/82765139/131322639-cd3ab117-5149-4071-975d-a5798cd75f8c.png)

**Comment by doktor83** [comment]
That parameter is working, but i see you are testing cryptonight_turtle, on Ryzens intensity 1 is forced, no matter what you set.
On Intel cpu's it accepts values 1 & 2 because it uses different code.

Honestly when i added cryptonight_turtle i wasn't giving it too much attention, that's why the 2 and 4 hashes / thread is missing.

Message "Algorithm 0 available values for --cpu-threads-intensity : 1, 2" is posted always to tell the user which are valid values for that algorithm, and you can see in the log intensity values for every thread separately.

Looks something like this :

[2021-08-30 15:57:54] Worker thread0 : CPU [2]
[2021-08-30 15:57:54] Worker thread1 : CPU [2]
[2021-08-30 15:57:54] Worker thread2 : CPU [2]
[2021-08-30 15:57:54] Worker thread3 : CPU [2]

Where [2] meanse that particular thread uses intensity 2.

You can set every cpu worker thread a separate intensity value. For ex : _--cpu-threads 4 --cpu-threads-intensity 1!2!1!2_

**Comment by Shai0Hulud** [comment]
Thanx for your answer, that explains it!

You mentioned that the 2 and 4 hashes / thread is missing, any chance this will be added in a future release?

And do you know if there is some kind of list which algorithm accept which threas intensity? To be honest, I only knew 1 and 2 until now, didnt know there are algos accepting 4 (and more?).

Cheers!

**Comment by doktor83** [comment]
i literally answered your question and you ask me again the same thing :)

_But it seems that XMRig does accept 1 and 2 for cn/pico aka cn/trtl. Why is it not working with your Miner?_
**Honestly when i added cryptonight_turtle i wasn't giving it too much attention, that's why the 2 and 4 hashes / thread is missing.**

Intensity = hashes / (per) thread. So intensity 2 means 2 hashes per thread. It's the same thing.

There is no list, when you start miner with the selected algorithm you will get a hint what's the max intensity you can set.
Usually there is not much benefit with 2+ intensity on algorithms that don't use small scratchpads, like your cn/pico for example.

**Comment by Shai0Hulud** [comment]
Sorry, I missed that. Thanx again!

Looking forward to next release. Keep up the great work!
