### ISSUE TITLE
Unstable hashrade

### ISSUE THREAD

**Issue by Hancdf** [doktor83/SRBMiner-Multi#62]
Hello! I use SRBminer for RX570 in RAVEos on the AUTOLYKOS algorithm, my hashrate is not stable, but on HIVEos with the same settings and video cards, the hashrate is stable. Why does this happen?
![1](https://user-images.githubusercontent.com/88250203/136664916-7956a93d-1bb6-46a9-afdd-b3c6361b73d9.jpg)
![2](https://user-images.githubusercontent.com/88250203/136664917-dc407d96-11dd-4422-9cdc-7795f52341f1.jpg)

**Comment by Hancdf** [comment]
> TBH i have no idea, never tried RaveOS. Is the hashrate at poolside ok ?
I use RIG5 on RAVEos for 2MINERS pool all hashrate comes in. Compared to other miners, rejections are 4 times less. Thank you very much for such a miner. Can you make the correct hashrade mapping on RAVEos?
![3](https://user-images.githubusercontent.com/88250203/136685201-03b84876-f871-4304-af6d-e2ca8bcb72fc.jpg)

![4](https://user-images.githubusercontent.com/88250203/136685123-86832606-fe38-439e-a13b-f60cc6224692.jpg)

**Comment by heliosgnosis** [comment]
The problem is operator error,  update you drivers man,  you really had to ask this question here,   you are on linux,  use the terminal like all linux user's do not blame the softtware when you have not done your part and made sure your kernel and system is updated with the correct  means to run software.
