### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by luc1an24** [doktor83/SRBMiner-Multi#8]
Hi
I am trying to integrate your miner inside NiceHash Miner.
During the process I encountered some issues that are preventing me from complete integration.
1) During Eaglesong mining we get only 'Share above target' errors.
Possible reason for this would be: fixed xn1 length => supported additional byte from NiceHash
2) During Handshake mining stratum is disconnecting miner because xnsub is not supported
(mining.extranonce.subscribe) is not being sent therefore 'mining.set_extranonce' is not sent back
3) Could you please put in option to have "Benchmark" feature (report speeds every n-seconds; or each minute - currently report is every 3 minutes)  
4) Is there any reason why 'gpu_hashrate' is reported in its own object instead inside 'gpu_devices' in API report?

Thank you for your co-operation!

**Comment by doktor83** [comment]
Hi,
1. The way i create the nonce would need too much work to rewrite it to work with NH, so i'm probably not going to do it because no one is mining Eaglesong with GPU-s (at least not with SRB)
2. Fixed in next release
3. Benchmarking is not at my to-do list atm, i have much more important stuff to do with the miner
4. I don't remember :)
