### ISSUE TITLE
SRB Miner stopped working entirely

### ISSUE THREAD

**Issue by gntz555** [doktor83/SRBMiner-Multi#84]
So my PC crashed and now the miner failes to start. Deleting the unzpped folder of the miner and then unzipping a new folder of the miner doesn't help. It still gets the "...stopped working" issue immidiately. This shows that there must be corrupted files on my PC somewhere. But where?

**Comment by twoex** [comment]
Happened to me as well... For corrupt files, i ran scannow /sfc in administrative command prompt

Definitely something was up as I noticed it's forcing some ip address server that fails to connect as well

**Comment by doktor83** [comment]
> So my PC crashed and now the miner failes to start. Deleting the unzpped folder of the miner and then unzipping a new folder of the miner doesn't help. It still gets the "...stopped working" issue immidiately. This shows that there must be corrupted files on my PC somewhere. But where?

i would say your antivirus deleted or blacklisted the miner .exe

**Comment by twoex** [comment]
I always check anti-virus and add expectations beforehand as its a common issue/solution... Although this time, definitely wasn't right... I know I'm responding to other people's comments but its because same issue is experienced...  And i thought I was the only one, why I never mentioned anything....

So trying to be helpful and provide input

**Comment by doktor83** [comment]
A log file might be useful.
--log-file log.txt --extended-log
